#!/bin/env python


def gen_server(build_context: str, dockerfile: str):
    return (
        f"\n  server:"
        f"\n    container_name: server"
        f"\n    build:"
        f"\n      context: {build_context}"
        f"\n      dockerfile: {dockerfile}"
        f"\n    volumes:"
        f"\n      - ./server/config.ini:/config.ini"
    )


def gen_client(id: int, build_context: str, dockerfile: str):
    client = f"client{id}"
    return (
        f"\n  {client}:"
        f"\n    container_name: {client}"
        f"\n    build:"
        f"\n      context: {build_context}"
        f"\n      dockerfile: {dockerfile}"
        f"\n    depends_on:"
        f"\n      - server"
        f"\n    environment:"
        f"\n      - CLI_ID={id}"
        f"\n    volumes:"
        f"\n      - ./client/config.yaml:/config.yaml"
    )


def gen_compose(
    clients: int, build_context: str, client_dockerfile: str, server_dockerfile: str
):
    compose = "services:"
    compose += gen_server(build_context, server_dockerfile)
    for c in range(1, clients + 1):
        compose += gen_client(c, build_context, client_dockerfile)

    return compose


def main():
    import sys

    BUILD_CONTEXT = "."
    SERVER_DOCKERFILE = "server/Dockerfile"
    CLIENT_DOCKERFILE = "client/Dockerfile"

    args = sys.argv

    if len(args) != 3:
        print(f"Usage:\n{args[0]} <filename> <clients>")
        sys.exit(1)

    filename = args[1]
    clients = int(args[2])

    with open(filename, "w") as f:
        compose = gen_compose(
            clients, BUILD_CONTEXT, CLIENT_DOCKERFILE, SERVER_DOCKERFILE
        )
        f.write(compose)


if __name__ == "__main__":
    main()
